# Generated by Django 3.2.7 on 2021-09-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroapi', '0002_auto_20210915_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='publishers',
            new_name='publisher',
        ),
    ]
